### ISSUE TITLE
Creating toggle with variant via curl

### ISSUE THREAD

**Issue by reiinoldo** [Unleash/unleash#1523]
### Describe the bug

I'm trying to add a toggle with variant via cURL / Postman and the variant is never inserted, only by the Admin panel is possible. 
Even if I pass the values `weightType, stickiness, payload`  it's not being inserted the `variants` property, it is always included as an empty array.

### Steps to reproduce the bug

Command used
```
curl --request POST \
  --url http://localhost:4242/api/admin/features \
 -H "Authorization: INSERT_API_KEY"
  --data '{"name":"featureX","description":"Toggles featureX on and off","type":"release","enabled":true,"stale":false,"strategies":[{"name":"default","editable":true,"description":"Default on/off strategy.","parameters":{"parameter":{"name":"groupId","type":"string","description":"Define activation groups to allow you to correlate across feature toggles.","required":false}}}],"variants":[{"name":"yellow","weight":20}]}'

```

response: 201
```

{
    "name": "featureX",
    "description": "Toggles featureX on and off",
    "type": "release",
    "project": "default",
    "stale": false,
    "variants": [],
    "createdAt": "2022-04-22T20:16:38.034Z",
    "lastSeenAt": null,
    "impressionData": false
}
```

![image](https://user-images.githubusercontent.com/7297915/164787798-1a0b36d1-3270-472d-903a-0f21107bf271.png)

Environment: 

docker-compose.yml
```
version: '3.7'

services:
  unleashdb:
    image: postgres:14
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    expose:
      - 5432
  unleashserver:
    image: unleashorg/unleash-server:4.8.2
    environment:
      - DATABASE_URL=postgres://postgres:unleash@unleashdb/postgres
      - DATABASE_SSL=false
      - AUTH_ENABLE_API_TOKEN=false
      - AUTH_TYPE=NONE
    depends_on:
      - unleashdb
```

### Expected behavior

```
{
    "name": "featureX",
    "impressionData": false,
    "description": "Toggles featureX on and off",
    "project": "default",
    "stale": false,
    "variants": [
        {
            "name": "yellow",
            "weight": 1000,
            "weightType": "variable",
            "stickiness": "default",
            "payload": {
                "type": "string",
                "value": "20"
            },
            "overrides": []
        }
    ],
    "createdAt": "2022-04-22T16:38.034Z",
    "lastSeenAt": null,
    "type": "release",
    "archived": false
}
```

![image](https://user-images.githubusercontent.com/7297915/164789161-aea6abf2-78b3-415b-b94f-f9f2490d930f.png)

### Unleash version

Unleash-server:4.8.2
