### ISSUE TITLE
feat: User Activity Tracker

### ISSUE THREAD

**Issue by dosuken123** [Unleash/unleash#653]
## Summary

In [the engineering discovery for GitLab A/B testing](https://gitlab.com/gitlab-org/gitlab/-/issues/280536), we took an approach to introduce [Event API](https://gitlab.com/gitlab-org/gitlab/-/issues/280536#step-1-introduce-event-api-to-collect-analytics-data-from-unleash-client) to track both user activity and feature toggle events for calculating conversion rates that how many users actually engaged a specific action per toggle variant.

Traditionally, user activity tracker (e.g. Google Analytics) and feature toggle system (e.g. Unleash) were/are separate services.
Given the nature of GitLab's [single platform for entire DevOps lifecycle](https://about.gitlab.com/stages-devops-lifecycle/) direction, it'd make more sense to integrate these two systems into one unified service. This is a similar reasoning with [why we integrated CI/CD into SVC platform](https://about.gitlab.com/blog/2020/10/29/gitlab-hero-devops-platform/) and how it was successful.

### Proposal 1: Introduce User Activity/Event API

Introduce [Event API](https://gitlab.com/gitlab-org/gitlab/-/issues/280536#step-1-introduce-event-api-to-collect-analytics-data-from-unleash-client) to record/persist user activity through the following payload:

```
events:
  - recorded_at: # When the event happened   e.g. `2020-11-02T13:15:34.787Z`
    name:        # What event happened       e.g. `user-visits-new-project-page`, `toggle-a`
    context:     # Who made the event        e.g. `jhon`
    type:        # The type of event.        e.g. `engage`, `feature-toggle`
    output:      # The output of event.      e.g. `blue`, `red`, etc
```

This allows us to collect accurate/detailed user activity in an application, which can be visualized flexibly from various aspect. For example, the collected data can be illustrated [as A/B testing result](https://gitlab.com/gitlab-org/gitlab/-/issues/280536#step-2-visualize-the-event-data-as-an-experiment) by aggregating base event and conversion event. It's even possible to show a general usage count, such as a click rate on a button.

A performance implication of this approach is that a payload size of `events` linearly increase by the number of events. This could be a bottle neck in a large application that has many active users. To reduce an unnecessary network I/O, it'd be better to give an option to turn the event recording off when it's unnecessary. Also, reducing the outbound traffic with a middle ware, such as [Unleash Proxy](https://www.unleash-hosted.com/articles/the-unleash-proxy/), is also an important factor for the further optimization.

### Proposal 2: Extend Metrics API

Extending [Metrics API](https://github.com/Unleash/unleash/blob/master/docs/api/client/metrics-api.md) to record/persist user activity through `events` key:

```
bucket:
  start:                 # DateTime
  stop:                  # DateTime
  toggles:               # Toggle Metrics
    toggle_name:
      variant_name:      # The access count per variant 
  events:                 # User Activity Metrics (New)
    event_name:          # The engage count per event
```

This is a dynamic approach that it produces A/B testing metrics by taking a diff of engage count per variant weight setup. For example,

1. Set the variant weight to "blue" is 100% and "red" is 0%
1. Take a snapshot of engage count
1. Change the weight to "blue" is 0% and "red" is 100%
1. Take a snapshot of engage count again
1. Compare 2. and 4. engage count

A performance implication of this approach is less severe compared to proposal 1, as basically unleash-client can reuse the existing polling mechanizm for metrics API.

**Comment by go-orit** [comment]
@ivarconr Can you tell us if the API specification is ok?

**Comment by ivarconr** [comment]
Hi, I have been thinking about this for a while. I am heavily leaning towards "proposal 1", as it gives us a lot of flexibility to change how we aggregate things later. I also believe your suggestion on using the Unleash Proxy between the SDK and Unleash API can be a great idea to facilitate some of the processing. 

I would like to change the spec slightly to make it more concrete: 

```yaml
events:
  - recorded_at: # When the event happened   e.g. `2020-11-02T13:15:34.787Z`
    name:        # What event happened       e.g. `user-visits-new-project-page`, `toggle-a`
    context:     # The full Unleash Context  (optional, static fields `environment` and `appName` will be added automatically). 
    type:        # The type of event.        e.g. `engage`, `feature-toggle`
    value:       # The output of event.      e.g. `blue`, `red`, etc
```

Also I think the SDK should batch these events and send them either in time based intervals or when the number of events is above a certain threshold. 

My biggest concerns are the amount of data this could produce in an environment, and I think we need to measure a bit on that.

We should also think about how this can be used in a real setup. Typically we have a feature toggle ("some-toggle") with two variants ("blue", "red). Example-data for this could be something like:

```yaml
events:
  - recorded_at: "2020-18-02T13:15:34.787Z"
    name: "some-toggle"
    context:
        environment: "prod"
        appName: "web-app"
        userId: "cb962f17-113b-4bdf-81ff-fa16041a95e3"
    type: "convert"  
    value: "red"
  - recorded_at: "2020-18-02T13:15:33.788Z"
    name: "some-toggle"
    context:
        environment: "prod"
        appName: "web-app"
        userId: "a2a17edd-dad9-431b-9365-99d78e3b9f16"
    type: "convert"  
    value: "blue"
```


I strongly believe this is something we can work with.

**Comment by ivarconr** [comment]
Also having this in place in the SDK, we could consider also allow this information to sent to other analytics tools as well, via custom registered functions.

**Comment by sveisvei** [comment]
Maybe support both - and make it optional to send the full events?

I would also support doing time based batching.

**Comment by ivarconr** [comment]
> Maybe support both - and make it optional to send the full events?

Maybe if we see the need.

**Comment by ivarconr** [comment]
A concrete example for my suggestion in [previous comment](https://github.com/Unleash/unleash/issues/653#issuecomment-731183709)

```yaml
events:
  - recorded_at: "2020-18-02T13:15:34.787Z"
    name: "newButton.red.view"
    context:
        environment: "prod"
        appName: "web-app"
        userId: "cb962f17-113b-4bdf-81ff-fa16041a95e3"
  - recorded_at: "2020-18-02T13:15:33.788Z"
    name: "newButton.red.convert"
    context:
        environment: "prod"
        appName: "web-app"
        userId: "cb962f17-113b-4bdf-81ff-fa16041a95e3"
```

**Comment by ivarconr** [comment]
**Iteration 2: split the name.** 
We could of course split the name in to its respective parts: 

```yaml
events:
  - recorded_at: # When the event happened   e.g. `2020-11-02T13:15:34.787Z`
    name:        # Event group name          e.g. `feature-toggle`
    variant:     # (optional) Event variant  e.g. `red`, `blue`
    action:      # what happend              e.g. `view`, `click`, `buy`, `play`, `pause`
    context:     # The Unleash Context  
    value:       # (optional) A numeric output of event.      e.g. `10.0`, `1.0`, etc
```

This feels a bit more verbose, and I am unsure if it is easier from a user of the Client SDK. We would probably need to standardize the actions, to ease the work of calculating conversions on the server side.

**Comment by dosuken123** [comment]
@ivarconr 

> I think the SDK should batch these events and send them either in time based intervals or when the number of events is above a certain threshold. My biggest concerns are the amount of data this could produce in an environment, and I think we need to measure a bit on that.

In [the PoC work](https://github.com/dosuken123/unleash-client-ruby/pull/1/files), I took the time based interval approach, like SDK already did for Metrics API. I also have the same concern that the Unleash server and client(s) shouldn't be overloaded by the new API. So the granularity of the events is a key.

Since the precision of `recorded_at` is millisecond level, if a user engaged a specific action twice with a slight delay, that produces double-sized payload. I'm not really sure if we need that level of precision, and looking for more pragmatic approach. One approach is to send `events` data batch at the fixed interval (e.g. just re-use [`metrics_interval`](https://github.com/Unleash/unleash-client-ruby#list-of-arguments)) with counting per _unique_ event. For example:

```yaml
start:     # When SDK started recording the events
stop:     # When SDK stopped recording the events
appname/instanId:  # Same with Metrics API
events:
  - name/variant/action/context/value: # Same as above
    count: # How many this unique event happened in the start-stop period
```

If the same event happened twice, the `count` is incremented by 1. SDK should be able to easily handle this.

**Comment by dosuken123** [comment]
> Also having this in place in the SDK, we could consider also allow this information to sent to other analytics tools as well, via custom registered functions.

This is really cool if possible. I think that some customers can't leave from their analytics tools by company policy or compliance.

**Comment by dosuken123** [comment]
@ivarconr Thank you for the thoughtful comment. It's very helpful to brush up the proposal!

> q1: How can this be connected on the server-side?

I think there are three main processes in [the A/B testing feature](https://gitlab.com/gitlab-org/gitlab/-/issues/280536).

1. A SDK records and sends events to a server
1. A server persists the events as-is
1. A server presents the persisted data in a fancy way

The 1. and 2. should be as straight-forward as possible, which basically does not concern how the recorded data is presented at 3.

From database query perspective at 3., it's ideal to persist event-name, type and output separately as the queries will be more flexible and performant to search specific type of events. Technically, your proposal that concatenates these into one sting in `name` should work too. (In GitLab, we rarely use [Pattern Matching query](https://www.postgresql.org/docs/8.1/functions-matching.html) due to performance reason, but it should work perfectly fine for small amount of rows)

> q2: How can this be connected to toggles with variants?

If it's variant type, the `type` will be `variant`. So for example,

```yaml
name: my-awesone-flag
context: jhon
type: variant
output: blue
```

Similarly, we can use the same format for boolean toggle.

```yaml
name: my-awesone-flag
context: jhon
type: toggle # or maybe "boolean"
output: true
```

As you proposed, these separate attributes can be concatenated into one a string like `#{name}.#{type}.#{output}`. The reason for the separation at my initial proposal is all for database query performance reason described above.

> q3: What is this event value?

Sometimes, it's useful to record an output of an event. Like you mentioned, purchase amount would be a good candidate.

For example, there is an eCommerce site. One day a product manager was wondering if changing "Add to cart" button color would encourage end-user's to buy more stuff. In this case, they can define events as the following:

Event 1: We can track who saw which color of the button. This event 

 Here is an example event:

````
name: purchase-color-of-button
type: variant
context: jhon
output: red  # or blue
````


Event 2: Feature Flag

A business metric about purchase amount can be additionally recorded. Here is an example event:

````
name: purchased-amount
type: engage 
context: jhon
output: 100
````

Now server side know that 

> q4: What happen to the event type

I'm currently under the impression that `event` type should be explicitly set in order to distinguish flag-base-event and generic-event, but I'm happy to discuss further.

**Comment by ivarconr** [comment]
Thanks for your wonderful explanations @dosuken123! Answering this required me to have some time to think about the problem. 

> NOTE: This event is automatically recorded when a SDK evaluated a feature flag

thanks, this was an important note that I did not catch. It makes sense for the SDK to record these automatically.

I do worry about the **amount of data though**. Would it make sense to introduce a property on the feature toggle level to say "collect detailed metrics"? (thinking out loud!).

> Technically, your proposal that concatenates these into one sting in name should work too

I proposed this, because I was concerned about two things;

1) **Data on the network.** If serialize this as json it could be a lot of extra, duplicate data sent. It could be we can neglect this by utilizing proper compression (gzip or similar) on the client side. If we had a formal protocol for the name the server could theoretically parse out the various parts and store it however it like in the database. However, if we can avoid this kind of parsing (a lot of edge cases to consider), that have huge benefits as well

2) **API surface for the user.** If the user was to send all these metrics manually, and having to put in the name, type, context and output correctly it would be a lot of effort and easy to get wrong. If the only types the user would need to do manually would be the "engage" types, I think the number of arguments could be heavily simplified for the user. 

However, this is something we can optimize if we agree on the concepts! 

> I'm currently under the impression that event type should be explicitly set in order to distinguish flag-base-event and generic-event, but I'm happy to discuss further.

Do you have any idea which types that we need to support? Is it important that we define them all up front?

Possible types:
- `boolean` (toggle)
- `variant`
- `engage` (business)

### The format
I do like your suggestion to count for a period of time, allowing us to aggregate and potentially reduce the load. We can always change this later. 

Have you thought about how to deal with "anonymous" users? We could simply omit the `userId` field from the context, and thus the count would really help reduce the network load. It would also be possible to fallback to using the `sessionId` instead, to have something which at-least follow the same user within a session. If we go down this path, I fear the "counting mechanism" is not going to be very helpful in practice. 

For context fields I feel we should have the "static context fields" on top (to reduce load, they will not change), and have "mutable context fields" as part of the event counts. 

Example identified users:
```yaml
start:     # When SDK started recording the events
stop:      # When SDK stopped recording the events
appName: demoApp
environment: production
events:
  - name: some-toggle-name
    type: variant
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: red
    count: 10
  - name: purchased-amount
    type: engage
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: 100 #optional
    count: 1
```
*) counting will need to take in to account all fields of the event (name, type, context and value). 

Example anonymous users:
```yaml
start:     # When SDK started recording the events
stop:      # When SDK stopped recording the events
appName: demoApp
environment: production
events:
  - name: some-toggle-name
    type: variant
    value: red
    count: 1000
  - name: purchased
    type: engage
    count: 100
```

It is still a bit unclear to me how we will connect the `engage` events with the correct `variant/boolean` events on the server side, but I guess we just need to create a UI to facilitate this. 

For me the next step would be to create a small PoC of the format itself to see how easy it is to use this data to create useful insights.

**Comment by dosuken123** [comment]
@ivarconr 

> It is still a bit unclear to me how we will connect the engage events with the correct variant/boolean events on the server side, but I guess we just need to create a UI to facilitate this.

I think this is the most important point on this issue, so let me clarify a bit further.

Let's say there are the following persisted event data on the server, that sent by a client:

`timestamps` table

| id  | start_at              | stop_at               |
| --- |-----------------------|---------              |
| 1   | `2020-11-02T10:00:00` |`2020-11-02T10:00:30`  |

`context` table

| id  | userId                |
| --- |-----------------------|
| 1   | `jhon`                |
| 2   | `cathy`               |
| 3   | `bob`                 |

`events` table

| timestamp_id (FK)         | Name                         | Type        | context_id (FK) | Value  | Count |
|-----------------------    |---------                     |------       | --------        |------  |-------|
| 1                         | purchase-button-color        | variant     | 1               | red    | 1     |
| 1                         | purchase-button-color        | variant     | 2               | red    | 1     |
| 1                         | purchase-button-color        | variant     | 3               | blue   | 1     |
| 2                         | user-purchase-item           | engage      | 1               | 100    | 1     |
| 2                         | user-purchase-item           | engage      | 2               | 100    | 1     |


For A/B testing, we introduce a new table for the definition of the experiment.

`experiments` table

| Title                              | Base Event Name        | Base Event Type | Base Event Output | Conversion Event Name | Conversion Event Type | Conversion Event Value |
|-----------------------             |------                  | --------        | -----             | -----                 | ---                   | ---                    |
| What button color is the best?     | purchase-button-color  | variant         | blue              | user-purchase-item    | engage                |                        |

And we can show experiment results by aggregating the above data:

Experiment: "What button color is the best?"

| Variant     | Unique Visitors | Conversions | Conversion Rate | Change |
|-------------|-----------------|-------------|-----------------|--------|
| blue (BASE) | 1               | 0           | 0.0             | N/A    |
| red         | 2               | 2           | 100.0           | +100.0 |

- `Variant` => The list of variants that users saw. Selecting `events.value` by `experiments`'s base event name and type.
- `Unique Visitors` => How many unique users saw the variant. Counting `events` rows by `experiments`'s base event name and type per variant.
- `Conversions` => How many unique users were converted by the variant. Counting `events` rows by `experiments`'s conversion event name and type per variant.
- `Conversion Rate` => (`Conversions` / `Unique Visitors`) * 100.0
- `Change` => The conversion rate change based on the base variant.

A few notes:
- DB queries should be optimized in order to avoid N+1
- There is a PoC screen shot in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46649 (GitLab ver)

**Comment by afontaine** [comment]
I think this is a pretty good idea to bridge the gap between variants and full A/B testing 

I think I would prefer to have an `/events` endpoint to hit to reduce the migration burden on client writers. Would `/metrics` eventually just go away here?

I also think the plan to bucket events is a good one. This is the way metrics already work, so extending that code wouldn't be a challenge, and it keeps data collection consistent. I suspect keeping track of a `count` on the client side will be challenging or expensive though, as these events are not _just_ keyed off name when counts and contexts are included:

```yaml
start:     # When SDK started recording the events
stop:      # When SDK stopped recording the events
appName: demoApp
environment: production
events:
  - name: some-toggle-name
    type: variant
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: red
  - name: purchased-amount
    type: engage
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: 100 #optional
  - name: some-toggle-name
    type: variant
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: red
  - name: purchased-amount
    type: engage
    context:
       userId: cb962f17-113b-4bdf-81ff-fa16041a95e3
    value: 100 #optional
```

I think there should be a strong emphasis on including the entire context for simplicity. I could foresee `toggle` and `variant` events attempt to only include context values that are the "deciding" factor. If a `flexibleRollout` is pinned to `sessionId`, then it's more important that that is what shows up in the event than other context values. That adds complexity that imo is unnecessary though (what do you do with multiple `true` strategies, etc.)

We'd have to supply a `record_event` function for users to track `engage` events (`record_engagement(name, value, context)`?), but the public API surface is still fairly small here: `is_enabled`, `get_variant` and `record_engagement`
