### ISSUE TITLE
Easier DB CA certificate configuration

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#6718]
### Describe the feature request

I'd like to have an ability to configure path to CA certificate instead of having to put file contents as an environment variable. Currently it's only possible by creating my own Docker image.

### Background

When using AWS Helm chart it's hard to interpolate variables, like reading file contents with `cat`. Shell is not available. Also, CA files can be longer then allowed secret length.

### Solution suggestions

In addition to `DATABASE_SSL` if we add an environment variable like `DATABASE_CA` we can point it to a file mounted in RDS.

```
volumeMounts:
        - name: rds-pem
          mountPath: /certificates
env:
          DATABASE_HOST: dfdsfdsfdfdfdf.rds.amazonaws.com
          DATABASE_NAME: unleash
          DATABASE_CA: /certificates/regional-bundle.pem
```

### Other informations
Request source: https://unleash-community.slack.com/archives/C03GWTN7XMG/p1711446883483999
Internal ticket: https://linear.app/unleash/issue/SR-509/easier-db-ca-certificate-configuration
