### ISSUE TITLE
Frontend returns 404 after running a few days

### ISSUE THREAD

**Issue by TapTap21** [Unleash/unleash#7337]
### Describe the bug

I run unleash in EKS with ALB ingress to the frontend. After it's been running a few days, the frontend returns 404 and simply loads a grey screen. Restarting the pods fixes it immediately. The healthcheck never fails during this issue.

### Steps to reproduce the bug

1.  Run unleash in kubernetes with ALB ingress
2.  Wait some time
3. Returns 404
4. Restart pod
5. Works

### Expected behavior

It does not return 404

### Logs, error output, etc.

```bash
I don't see anything weird in the logs
```

### Screenshots

![image](https://github.com/Unleash/unleash/assets/31740134/b061d99a-0d99-4fdb-a9cb-195e5e0949d5)

### Additional context

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: 'true'
  name: unleash
  namespace: unleash
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: unleash-prod
      app.kubernetes.io/name: unleash
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: 'true'
        app.kubernetes.io/instance: unleash-prod
        app.kubernetes.io/name: unleash
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: unleash
            - configMapRef:
                name: unleash
          image: 'unleashorg/unleash-server:latest'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          name: unleash
          ports:
            - containerPort: 4242
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 1
            periodSeconds: 2
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 256Mi
      nodeSelector:
        provisioner: karpenter
      restartPolicy: Always
      terminationGracePeriodSeconds: 90
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: unleash-prod
              app.kubernetes.io/name: unleash
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: unleash-prod
              app.kubernetes.io/name: unleash
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule

```

### Unleash version

6.0.0

### Subscription type

None

### Hosting type

Self-hosted
