### ISSUE TITLE
Projects tab is not showing for me on admin UI

### ISSUE THREAD

**Issue by bashilbers** [Unleash/unleash#954]
Hey guys,

I do not seem to have a projects tab in my admin UI, see:

![image](https://user-images.githubusercontent.com/455905/134483352-bd6a1c3b-ede2-4755-82de-2b2582c1a58e.png)

I'm running the server via docker, here's my docker-compose:

```
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=some_password
            - POSTGRES_USER=unleash_user
            - POSTGRES_DB=unleash
        
    unleash:
        image: unleashorg/unleash-server
        ports:
            - 4242:4242
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_NAME=unleash
            - DATABASE_USERNAME=unleash_user
            - DATABASE_PASSWORD=some_password
            - DATABASE_SSL=false
        depends_on:
            - postgres
```

I've tried creating multiple users with different roles, but I never get the projects tab as seen in the documentation on how to create a new project.

Any ideas on what is going on? Why is my projects tab not showing? :-(
